// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.3
// source: message_service/message/v1/update_message_status.proto

package messagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMessageStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *UpdateMessageStatusRequest) Reset() {
	*x = UpdateMessageStatusRequest{}
	mi := &file_message_service_message_v1_update_message_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusRequest) ProtoMessage() {}

func (x *UpdateMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_service_message_v1_update_message_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_message_service_message_v1_update_message_status_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMessageStatusRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_message_service_message_v1_update_message_status_proto protoreflect.FileDescriptor

var file_message_service_message_v1_update_message_status_proto_rawDesc = []byte{
	0x0a, 0x36, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x28, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b,
	0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x42, 0x2a, 0x5a, 0x28, 0x61,
	0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_service_message_v1_update_message_status_proto_rawDescOnce sync.Once
	file_message_service_message_v1_update_message_status_proto_rawDescData = file_message_service_message_v1_update_message_status_proto_rawDesc
)

func file_message_service_message_v1_update_message_status_proto_rawDescGZIP() []byte {
	file_message_service_message_v1_update_message_status_proto_rawDescOnce.Do(func() {
		file_message_service_message_v1_update_message_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_service_message_v1_update_message_status_proto_rawDescData)
	})
	return file_message_service_message_v1_update_message_status_proto_rawDescData
}

var file_message_service_message_v1_update_message_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_service_message_v1_update_message_status_proto_goTypes = []any{
	(*UpdateMessageStatusRequest)(nil), // 0: message_service.message.v1.UpdateMessageStatusRequest
}
var file_message_service_message_v1_update_message_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_service_message_v1_update_message_status_proto_init() }
func file_message_service_message_v1_update_message_status_proto_init() {
	if File_message_service_message_v1_update_message_status_proto != nil {
		return
	}
	file_message_service_message_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_service_message_v1_update_message_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_service_message_v1_update_message_status_proto_goTypes,
		DependencyIndexes: file_message_service_message_v1_update_message_status_proto_depIdxs,
		MessageInfos:      file_message_service_message_v1_update_message_status_proto_msgTypes,
	}.Build()
	File_message_service_message_v1_update_message_status_proto = out.File
	file_message_service_message_v1_update_message_status_proto_rawDesc = nil
	file_message_service_message_v1_update_message_status_proto_goTypes = nil
	file_message_service_message_v1_update_message_status_proto_depIdxs = nil
}
